"""Motion-reference command, observations, and rewards for hybrid imitation.

This is the mjlab port of the *data contract* used by BeyondMimic's G1
``MotionCommand``: a reference ``.npz`` carries named joint trajectories plus
world-frame body pose and velocity trajectories.  Keeping the names in the
file is intentional: silently relying on a joint order is unsafe for humanoid
imitation, especially when a G1 clip is used with a different articulation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
import torch
from mjlab.managers.command_manager import CommandTerm, CommandTermCfg
from mjlab.managers.scene_entity_config import SceneEntityCfg
from mjlab.utils.lab_api.math import quat_apply, quat_inv, quat_mul, yaw_quat

from training_common.reference_centroidal import (
  ReferenceCentroidalTrajectory,
  compute_reference_centroidal,
  prealign_reference_kinematics_to_initial_anchor,
)

if TYPE_CHECKING:
  from mjlab.envs import ManagerBasedRlEnv


@dataclass(kw_only=True)
class MotionReferenceCommandCfg(CommandTermCfg):
  """Named BeyondMimic reference-motion stream.

  ``motion_file`` deliberately defaults to ``None``.  The repository ships a
  THEMIS model, not a G1 MJCF, so making a G1 clip the implicit default would
  create an invalid task.  A G1 task must provide both its G1 entity and a G1
  clip with matching ``joint_names``/``body_names`` metadata.
  """

  asset_cfg: SceneEntityCfg = field(default_factory=lambda: SceneEntityCfg("robot"))
  motion_file: str | None = None
  joint_names: tuple[str, ...] = ()
  body_names: tuple[str, ...] = ()
  anchor_body_name: str = ""
  # Bodies used for mass-consistent reference CoM/momentum reconstruction.
  # Pass every articulated reference body for an exact whole-body result.
  centroidal_body_names: tuple[str, ...] = ()
  # Legacy centroidal-only canonicalization. New mimic configurations should
  # use ``reference_frame_alignment='initial_anchor'`` so body tracking and
  # centroidal planning share exactly one static reference frame.
  prealign_centroidal_to_initial_anchor: bool = False
  # Static clip transform applied exactly once at load time. ``initial_anchor``
  # removes the initial anchor x/y and yaw but preserves height, roll/pitch,
  # joint motion and subsequent root translation. It is deliberately distinct
  # from BeyondMimic's runtime robot-error alignment in ``aligned_body_pos_w``.
  reference_frame_alignment: str = "initial_anchor"  # "none" | "initial_anchor"
  # Designated bodies whose reference origins (or configured offsets) are
  # exported as candidate MPC contact points.  Their online continuous contact
  # activation is generated by the fast RL action, not a standalone network.
  contact_body_names: tuple[str, ...] = ()
  contact_point_offsets_b: dict[str, tuple[float, float, float]] = field(default_factory=dict)
  # Optional [T, C] contact labels stored in the reference NPZ.  If omitted,
  # labels are inferred once from candidate-contact height and speed.
  reference_contact_key: str | None = None
  reference_contact_height_threshold: float = 0.03
  reference_contact_speed_threshold: float = 0.35
  reference_contact_min_stance_frames: int = 3
  reference_contact_min_swing_frames: int = 2
  loop: bool = True
  random_start: bool = True
  resampling_time_range: tuple[float, float] = (1.0e9, 1.0e9)

  def build(self, env: "ManagerBasedRlEnv") -> "MotionReferenceCommand":
    return MotionReferenceCommand(self, env)


@dataclass(frozen=True)
class MJLabMotionClip:
  """Named, immutable reference-trajectory tensors on the training device."""

  fps: float
  joint_pos: torch.Tensor
  joint_vel: torch.Tensor
  body_pos_w: torch.Tensor
  body_quat_w: torch.Tensor
  body_lin_vel_w: torch.Tensor
  body_ang_vel_w: torch.Tensor
  joint_names: tuple[str, ...]
  body_names: tuple[str, ...]
  source_motion_file: str
  # BeyondMimic/MJLab conversion writes CoM velocity.  The explicit field
  # also keeps CPU-trimmed (origin-Jacobian) clips physically unambiguous.
  body_linear_velocity_point: str

  @property
  def num_frames(self) -> int:
    return int(self.joint_pos.shape[0])


class MJLabMotionLoader:
  """Load and validate the BeyondMimic NPZ contract for MJLab training.

  Offline conversion owns temporal resampling and velocity differentiation;
  this loader deliberately does not resample again, because re-interpolating
  body poses independently at training time would break kinematic and
  centroidal consistency.  It only validates metadata and transfers the
  immutable clip to the simulation device.
  """

  _REQUIRED = {
    "fps", "joint_pos", "joint_vel", "body_pos_w", "body_quat_w",
    "body_lin_vel_w", "body_ang_vel_w", "joint_names", "body_names",
  }

  def __init__(self, path: Path, device: torch.device | str):
    if not path.is_file():
      raise FileNotFoundError(f"Motion reference does not exist: {path}")
    with np.load(path, allow_pickle=False) as data:
      missing = self._REQUIRED.difference(data.files)
      if missing:
        raise ValueError(f"{path} is not a BeyondMimic reference NPZ; missing {sorted(missing)}")
      fps = float(np.asarray(data["fps"]).reshape(-1)[0])
      if fps <= 0.0:
        raise ValueError(f"Motion fps must be positive, got {fps}")
      tensors = {
        name: torch.as_tensor(data[name], device=device, dtype=torch.float32)
        for name in ("joint_pos", "joint_vel", "body_pos_w", "body_quat_w", "body_lin_vel_w", "body_ang_vel_w")
      }
      joint_names = tuple(str(name) for name in data["joint_names"].tolist())
      body_names = tuple(str(name) for name in data["body_names"].tolist())
      source = str(np.asarray(data.get("source_motion_file", "")).reshape(-1)[0])
      velocity_point = str(np.asarray(data.get("body_linear_velocity_point", "inertial_com")).reshape(-1)[0])
      if velocity_point not in {"inertial_com", "link_origin"}:
        raise ValueError(
          "body_linear_velocity_point must be 'inertial_com' or 'link_origin', "
          f"got {velocity_point!r}"
        )
    self.path = path
    self.device = device
    self.clip = MJLabMotionClip(
      fps=fps, joint_names=joint_names, body_names=body_names,
      source_motion_file=source, body_linear_velocity_point=velocity_point, **tensors,
    )
    self._validate()

  def optional_tensor(self, key: str) -> torch.Tensor | None:
    """Read one optional, clip-level label without weakening the core contract."""
    with np.load(self.path, allow_pickle=False) as data:
      if key not in data.files:
        return None
      return torch.as_tensor(data[key], device=self.device, dtype=torch.float32)

  def _validate(self) -> None:
    clip = self.clip
    frames = clip.num_frames
    if frames < 2:
      raise ValueError("Motion reference needs at least two frames")
    if clip.joint_vel.shape != clip.joint_pos.shape:
      raise ValueError("joint_vel must have exactly the same [T,J] shape as joint_pos")
    if len(clip.joint_names) != clip.joint_pos.shape[1] or len(set(clip.joint_names)) != len(clip.joint_names):
      raise ValueError("joint_names must be unique and match joint_pos's second dimension")
    body_shape = (frames, len(clip.body_names))
    expected = {
      "body_pos_w": (*body_shape, 3), "body_quat_w": (*body_shape, 4),
      "body_lin_vel_w": (*body_shape, 3), "body_ang_vel_w": (*body_shape, 3),
    }
    for name, shape in expected.items():
      if tuple(getattr(clip, name).shape) != shape:
        raise ValueError(f"{name} has shape {tuple(getattr(clip, name).shape)}, expected {shape}")
    if len(set(clip.body_names)) != len(clip.body_names):
      raise ValueError("body_names must be unique")
    finite_fields = ("joint_pos", "joint_vel", *expected)
    if not all(bool(torch.isfinite(getattr(clip, name)).all()) for name in finite_fields):
      raise ValueError("Motion trajectory contains NaN or Inf")
    quat_norm = clip.body_quat_w.norm(dim=-1)
    if bool((quat_norm < 1.0e-6).any()):
      raise ValueError("body_quat_w contains a zero-norm quaternion")

  def joint_indices(self, names: tuple[str, ...]) -> torch.Tensor:
    lookup = {name: index for index, name in enumerate(self.clip.joint_names)}
    missing = [name for name in names if name not in lookup]
    if missing:
      raise ValueError(f"Reference motion has no requested joints: {missing}")
    return torch.tensor([lookup[name] for name in names], device=self.clip.joint_pos.device, dtype=torch.long)

  def body_indices(self, names: tuple[str, ...]) -> torch.Tensor:
    lookup = {name: index for index, name in enumerate(self.clip.body_names)}
    missing = [name for name in names if name not in lookup]
    if missing:
      raise ValueError(f"Reference motion has no requested bodies: {missing}")
    return torch.tensor([lookup[name] for name in names], device=self.clip.body_pos_w.device, dtype=torch.long)


class MotionReferenceCommand(CommandTerm):
  """MJLab counterpart of BeyondMimic ``MotionCommand``.

  It advances a named :class:`MJLabMotionClip` at simulation time, maps its
  q/dq and body channels to the active articulation, applies the static
  reference-frame transform once, and exposes both causal tracker references
  and non-causal centroidal MPC horizons.
  """

  cfg: MotionReferenceCommandCfg

  def __init__(self, cfg: MotionReferenceCommandCfg, env: "ManagerBasedRlEnv"):
    super().__init__(cfg, env)
    if not cfg.motion_file:
      raise ValueError(
        "commands.motion.motion_file is required. Provide a retargeted clip "
        "whose joint_names and body_names match the simulated robot."
      )
    self.motion = MJLabMotionLoader(Path(cfg.motion_file), self.device)
    clip = self.motion.clip
    self.fps = clip.fps
    self._q = clip.joint_pos
    self._dq = clip.joint_vel
    self._body_pos = clip.body_pos_w
    self._body_quat = clip.body_quat_w
    self._body_lin_vel = clip.body_lin_vel_w
    self._body_ang_vel = clip.body_ang_vel_w
    self._motion_joint_names = clip.joint_names
    self._motion_body_names = clip.body_names
    self.num_frames = clip.num_frames

    self._asset_cfg = cfg.asset_cfg
    self._asset_cfg.resolve(env.scene)
    self.robot = env.scene[self._asset_cfg.name]
    requested_joints = cfg.joint_names or tuple(self.robot.joint_names)
    joint_ids, resolved_joint_names = self.robot.find_joints_by_actuator_names(requested_joints)
    if len(joint_ids) != len(requested_joints):
      raise ValueError(f"Unresolved motion joint names: requested={requested_joints}, resolved={resolved_joint_names}")
    self.joint_ids = torch.tensor(joint_ids, device=self.device, dtype=torch.long)
    self.motion_joint_ids = self.motion.joint_indices(tuple(resolved_joint_names))

    requested_bodies = cfg.body_names or (cfg.anchor_body_name,)
    if not cfg.anchor_body_name:
      raise ValueError("commands.motion.anchor_body_name is required")
    body_ids, resolved_body_names = self.robot.find_bodies(requested_bodies)
    if len(body_ids) != len(requested_bodies):
      raise ValueError(f"Unresolved motion body names: requested={requested_bodies}, resolved={resolved_body_names}")
    self.body_ids = torch.tensor(body_ids, device=self.device, dtype=torch.long)
    self.motion_body_ids = self.motion.body_indices(tuple(resolved_body_names))
    try:
      self.anchor_index = list(resolved_body_names).index(cfg.anchor_body_name)
    except ValueError as exc:
      raise ValueError("anchor_body_name must be included in body_names") from exc

    if cfg.reference_frame_alignment not in {"none", "initial_anchor"}:
      raise ValueError("reference_frame_alignment must be 'none' or 'initial_anchor'")
    self._reference_frame_alignment = cfg.reference_frame_alignment
    if self._reference_frame_alignment == "initial_anchor":
      # Keep the source NPZ raw/provenance-preserving.  The deterministic
      # canonicalization belongs at command load, where its meaning is shared
      # by pose rewards, reference centroidal computation and MPC contacts.
      anchor_motion_id = int(self.motion_body_ids[self.anchor_index])
      self._body_pos, self._body_quat, self._body_lin_vel, self._body_ang_vel = (
        prealign_reference_kinematics_to_initial_anchor(
          body_pos_w=self._body_pos,
          body_quat_w=self._body_quat,
          body_lin_vel_w=self._body_lin_vel,
          body_ang_vel_w=self._body_ang_vel,
          anchor_body_index=anchor_motion_id,
        )
      )

    self._centroidal_body_names = cfg.centroidal_body_names or tuple(resolved_body_names)
    self._reference_centroidal = self._build_reference_centroidal(self._centroidal_body_names)
    self._reference_contact_state = self._load_or_infer_reference_contact_state()
    self._frame = torch.zeros(self.num_envs, dtype=torch.long, device=self.device)
    self._frame_progress = torch.zeros(self.num_envs, device=self.device)
    self.metrics["joint_pos_error"] = torch.zeros(self.num_envs, device=self.device)
    self.metrics["anchor_pos_error"] = torch.zeros(self.num_envs, device=self.device)

  @property
  def command(self) -> torch.Tensor:
    return torch.cat([self.joint_pos, self.joint_vel], dim=-1)

  @property
  def joint_pos(self) -> torch.Tensor:
    return self._q[self._frame][:, self.motion_joint_ids]

  @property
  def joint_vel(self) -> torch.Tensor:
    velocity = self._dq[self._frame][:, self.motion_joint_ids]
    # A non-looping clip has a static terminal reference. Retaining the last
    # finite-difference velocity would request motion beyond the data.
    if not self.cfg.loop:
      velocity = torch.where(
        (self._frame < self.num_frames - 1).unsqueeze(-1), velocity, torch.zeros_like(velocity)
      )
    return velocity

  @property
  def body_pos_w(self) -> torch.Tensor:
    return self._body_pos[self._frame][:, self.motion_body_ids] + self._env.scene.env_origins[:, None, :]

  @property
  def body_quat_w(self) -> torch.Tensor:
    return self._body_quat[self._frame][:, self.motion_body_ids]

  @property
  def body_lin_vel_w(self) -> torch.Tensor:
    return self._body_lin_vel[self._frame][:, self.motion_body_ids]

  @property
  def body_ang_vel_w(self) -> torch.Tensor:
    return self._body_ang_vel[self._frame][:, self.motion_body_ids]

  @property
  def robot_joint_pos(self) -> torch.Tensor:
    return self.robot.data.joint_pos[:, self.joint_ids]

  @property
  def robot_joint_vel(self) -> torch.Tensor:
    return self.robot.data.joint_vel[:, self.joint_ids]

  @property
  def robot_body_pos_w(self) -> torch.Tensor:
    return self.robot.data.body_link_pos_w[:, self.body_ids]

  @property
  def robot_body_quat_w(self) -> torch.Tensor:
    return self.robot.data.body_link_quat_w[:, self.body_ids]

  @property
  def reference_centroidal(self) -> ReferenceCentroidalTrajectory:
    """Current mass-consistent reference, placed in the simulator world."""
    return self._place_reference_centroidal_in_env(self._reference_centroidal.select(self._frame))

  def aligned_body_pos_w(self) -> torch.Tensor:
    """Anchor-align reference xy/yaw exactly as the BeyondMimic tracker does."""
    ref_anchor_pos = self.body_pos_w[:, self.anchor_index]
    ref_anchor_quat = self.body_quat_w[:, self.anchor_index]
    robot_anchor_pos = self.robot_body_pos_w[:, self.anchor_index]
    robot_anchor_quat = self.robot_body_quat_w[:, self.anchor_index]
    delta = yaw_quat(quat_mul(robot_anchor_quat, quat_inv(ref_anchor_quat)))
    anchor_target = robot_anchor_pos.clone()
    anchor_target[:, 2] = ref_anchor_pos[:, 2]
    return anchor_target[:, None, :] + quat_apply(delta[:, None, :], self.body_pos_w - ref_anchor_pos[:, None, :])

  def centroidal_horizon(self, steps: int, dt: float) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Return anchor pose/linear/angular velocity over an MPC horizon.

    The anchor is the retargeted torso/pelvis proxy for CoM.  This is the
    same reduced-order approximation used when the centroidal MPC operates
    without a full inverse-dynamics model.
    """
    offsets = torch.floor(torch.arange(steps, device=self.device) * self.fps * dt).long()
    frames = self._frame[:, None] + offsets[None, :]
    if self.cfg.loop:
      frames = frames.remainder(self.num_frames)
    else:
      frames = frames.clamp(max=self.num_frames - 1)
    motion_anchor = self.motion_body_ids[self.anchor_index]
    return (
      self._body_pos[frames, motion_anchor] + self._env.scene.env_origins[:, None, :],
      self._body_lin_vel[frames, motion_anchor],
      self._body_ang_vel[frames, motion_anchor],
    )

  def reference_centroidal_horizon(self, steps: int, dt: float) -> ReferenceCentroidalTrajectory:
    """Mass-consistent, simulator-world reference over the MPC horizon."""
    reference = self._place_reference_centroidal_in_env(
      self._reference_centroidal.select(self._horizon_frame_ids(steps, dt))
    )
    if self.cfg.loop:
      return reference
    valid = self.reference_horizon_valid(steps, dt)
    # The safe built-in tail is a static terminal pose. Dynamic clips should
    # instead contain an explicit recovery/standing tail in the source NPZ.
    zeros = torch.zeros_like(reference.com_vel_w)
    return ReferenceCentroidalTrajectory(
      com_pos_w=reference.com_pos_w,
      com_vel_w=torch.where(valid.unsqueeze(-1), reference.com_vel_w, zeros),
      linear_momentum_w=torch.where(valid.unsqueeze(-1), reference.linear_momentum_w, zeros),
      angular_momentum_w=torch.where(valid.unsqueeze(-1), reference.angular_momentum_w, zeros),
      contact_pos_w=reference.contact_pos_w,
      contact_pos_rel_com_w=reference.contact_pos_w - reference.com_pos_w.unsqueeze(-2),
    )

  def _place_reference_centroidal_in_env(
    self, reference: ReferenceCentroidalTrajectory,
  ) -> ReferenceCentroidalTrajectory:
    """Translate canonical centroidal positions into each environment world."""
    origins = self._env.scene.env_origins.to(
      device=reference.com_pos_w.device, dtype=reference.com_pos_w.dtype,
    )

    def _expand_origin(ndim: int) -> torch.Tensor:
      return origins.reshape(origins.shape[0], *([1] * (ndim - 2)), 3)

    def _translate(position: torch.Tensor) -> torch.Tensor:
      return position + _expand_origin(position.ndim)

    com_pos_w = _translate(reference.com_pos_w)
    contact_pos_w = _translate(reference.contact_pos_w)
    return ReferenceCentroidalTrajectory(
      com_pos_w=com_pos_w,
      com_vel_w=reference.com_vel_w,
      linear_momentum_w=reference.linear_momentum_w,
      angular_momentum_w=reference.angular_momentum_w,
      contact_pos_w=contact_pos_w,
      contact_pos_rel_com_w=contact_pos_w - com_pos_w.unsqueeze(-2),
    )

  def reference_contact_horizon(self, steps: int, dt: float) -> torch.Tensor:
    """Reference contact activations ``[B, steps, C]`` over an MPC horizon."""
    return self._reference_contact_state[self._horizon_frame_ids(steps, dt)]

  def reference_horizon_valid(self, steps: int, dt: float) -> torch.Tensor:
    """Return a valid-stage mask for non-looping future reference samples."""
    if steps < 1:
      raise ValueError("steps must be positive")
    if self.cfg.loop:
      return torch.ones(self.num_envs, steps, dtype=torch.bool, device=self.device)
    offsets = torch.floor(torch.arange(steps, device=self.device) * self.fps * dt).long()
    return self._frame[:, None] + offsets[None, :] < self.num_frames

  def joint_reference_frame_offset(self, frame_offset: int = 1) -> torch.Tensor:
    """One causal reference preview ``[q_ref, dq_ref]`` at a clip-frame offset."""
    if frame_offset < 0:
      raise ValueError("frame_offset must be non-negative")
    frames = self._frame + frame_offset
    if self.cfg.loop:
      frames = frames.remainder(self.num_frames)
    else:
      frames = frames.clamp(max=self.num_frames - 1)
    q = self._q[frames][:, self.motion_joint_ids]
    dq = self._dq[frames][:, self.motion_joint_ids]
    if not self.cfg.loop:
      valid = (self._frame + frame_offset) < self.num_frames
      dq = torch.where(valid.unsqueeze(-1), dq, torch.zeros_like(dq))
    return torch.cat([q, dq], dim=-1)

  def _horizon_frame_ids(self, steps: int, dt: float) -> torch.Tensor:
    offsets = torch.floor(torch.arange(steps, device=self.device) * self.fps * dt).long()
    frames = self._frame[:, None] + offsets[None, :]
    if self.cfg.loop:
      return frames.remainder(self.num_frames)
    return frames.clamp(max=self.num_frames - 1)

  def _resolve_reference_bodies(
    self, requested_names: tuple[str, ...], label: str
  ) -> tuple[torch.Tensor, torch.Tensor, tuple[str, ...]]:
    if not requested_names:
      empty = torch.empty(0, device=self.device, dtype=torch.long)
      return empty, empty, ()
    body_ids, resolved_names = self.robot.find_bodies(requested_names)
    if len(body_ids) != len(requested_names):
      raise ValueError(f"Unresolved {label} body names: requested={requested_names}, resolved={resolved_names}")
    name_to_motion = {name: i for i, name in enumerate(self._motion_body_names)}
    missing = [name for name in resolved_names if name not in name_to_motion]
    if missing:
      raise ValueError(f"Reference motion has no {label} bodies: {missing}")
    return (
      torch.tensor(body_ids, device=self.device, dtype=torch.long),
      torch.tensor([name_to_motion[name] for name in resolved_names], device=self.device, dtype=torch.long),
      tuple(resolved_names),
    )

  def _build_reference_centroidal(self, names: tuple[str, ...]) -> ReferenceCentroidalTrajectory:
    local_body_ids, motion_body_ids, resolved_names = self._resolve_reference_bodies(names, "centroidal")
    if not len(resolved_names):
      raise ValueError("centroidal_body_names (or body_names) must not be empty")
    global_ids = self.robot.indexing.body_ids[local_body_ids].detach().cpu().numpy()
    model = self._env.sim.mj_model
    dtype = self._body_pos.dtype
    def _model_field(name: str) -> torch.Tensor:
      return torch.as_tensor(np.asarray(getattr(model, name))[global_ids], device=self.device, dtype=dtype)
    mass = _model_field("body_mass")
    com_offset = _model_field("body_ipos")
    inertia = _model_field("body_inertia")
    inertial_quat = _model_field("body_iquat")
    name_to_centroidal = {name: index for index, name in enumerate(resolved_names)}
    missing_contacts = [name for name in self.cfg.contact_body_names if name not in name_to_centroidal]
    if missing_contacts:
      raise ValueError(
        "Every contact_body_name must also be included in centroidal_body_names "
        f"so a contact point can be expressed relative to the whole-body CoM: {missing_contacts}"
      )
    contact_indices = torch.tensor(
      [name_to_centroidal[name] for name in self.cfg.contact_body_names], device=self.device, dtype=torch.long
    )
    if self.cfg.contact_body_names:
      offsets = torch.tensor(
        [self.cfg.contact_point_offsets_b.get(name, (0.0, 0.0, 0.0)) for name in self.cfg.contact_body_names],
        device=self.device, dtype=dtype,
      )
    else:
      offsets = torch.empty(0, 3, device=self.device, dtype=dtype)
    body_pos_w = self._body_pos[:, motion_body_ids]
    body_quat_w = self._body_quat[:, motion_body_ids]
    body_lin_vel_w = self._body_lin_vel[:, motion_body_ids]
    body_ang_vel_w = self._body_ang_vel[:, motion_body_ids]
    if self.cfg.prealign_centroidal_to_initial_anchor and self._reference_frame_alignment == "none":
      try:
        anchor_index = list(resolved_names).index(self.cfg.anchor_body_name)
      except ValueError as exc:
        raise ValueError(
          "prealign_centroidal_to_initial_anchor requires anchor_body_name "
          "to be included in centroidal_body_names"
        ) from exc
      body_pos_w, body_quat_w, body_lin_vel_w, body_ang_vel_w = (
        prealign_reference_kinematics_to_initial_anchor(
          body_pos_w=body_pos_w,
          body_quat_w=body_quat_w,
          body_lin_vel_w=body_lin_vel_w,
          body_ang_vel_w=body_ang_vel_w,
          anchor_body_index=anchor_index,
        )
      )
    return compute_reference_centroidal(
      body_pos_w=body_pos_w,
      body_quat_w=body_quat_w,
      body_lin_vel_w=body_lin_vel_w,
      body_ang_vel_w=body_ang_vel_w,
      body_mass=mass,
      body_com_offset_b=com_offset,
      body_inertia_diag=inertia,
      body_inertial_quat_b=inertial_quat,
      contact_body_indices=contact_indices,
      contact_point_offset_b=offsets,
      body_linear_velocity_point=self.motion.clip.body_linear_velocity_point,
    )

  def _load_or_infer_reference_contact_state(self) -> torch.Tensor:
    """Load contact labels when present, otherwise infer a flat-ground prior.

    The fallback is intentionally only a nominal sequence for MPC.  It is not
    an online contact-prediction network: the fast RL action and simulated
    contact reward correct reference/simulation mismatch during training.
    """
    contacts = self._reference_centroidal.contact_pos_w
    n_contacts = contacts.shape[1]
    key = self.cfg.reference_contact_key
    if key is not None:
      labels = self.motion.optional_tensor(key)
      if labels is None:
        raise ValueError(f"reference_contact_key={key!r} is absent from {self.motion.path}")
      if labels.shape != (self.num_frames, n_contacts):
        raise ValueError(
          f"Reference contact labels {key!r} must have shape "
          f"[{self.num_frames}, {n_contacts}], got {tuple(labels.shape)}"
        )
      return labels.clamp(0.0, 1.0)
    if n_contacts == 0:
      return torch.empty(self.num_frames, 0, device=self.device)

    # For a flat reference clip, the lowest candidate-contact point for each
    # foot defines its nominal floor height.  A contact must be close to that
    # height and nearly stationary.  Use a central finite difference so the
    # first and final frames remain well-defined.
    height = contacts[..., 2]
    floor_height = height.amin(dim=0, keepdim=True)
    prev = torch.cat([contacts[:1], contacts[:-1]], dim=0)
    next_ = torch.cat([contacts[1:], contacts[-1:]], dim=0)
    speed = (next_ - prev).norm(dim=-1) * (0.5 * self.fps)
    candidates = (
      (height - floor_height <= self.cfg.reference_contact_height_threshold)
      & (speed <= self.cfg.reference_contact_speed_threshold)
    )
    return self._smooth_reference_contact_state(candidates).to(torch.float32)

  def _smooth_reference_contact_state(self, candidates: torch.Tensor) -> torch.Tensor:
    """Apply run-length hysteresis to kinematic contact candidates once per clip."""
    min_stance = self.cfg.reference_contact_min_stance_frames
    min_swing = self.cfg.reference_contact_min_swing_frames
    if min_stance < 1 or min_swing < 1:
      raise ValueError("reference contact minimum stance/swing duration must be at least one frame")
    state = candidates.clone()
    frames, contacts = state.shape
    # First fill very short gaps within a stance, then remove very short
    # isolated stance runs. This is deterministic preprocessing, not online
    # prediction, and prevents a one-frame contact mode from reaching MPC.
    for contact_id in range(contacts):
      for target_value, max_length, replacement in ((False, min_swing - 1, True), (True, min_stance - 1, False)):
        if max_length <= 0:
          continue
        start = 0
        while start < frames:
          value = bool(state[start, contact_id].item())
          end = start + 1
          while end < frames and bool(state[end, contact_id].item()) == value:
            end += 1
          if value == target_value and end - start <= max_length:
            left_matches = start > 0 and bool(state[start - 1, contact_id].item()) == replacement
            right_matches = end < frames and bool(state[end, contact_id].item()) == replacement
            if left_matches and right_matches:
              state[start:end, contact_id] = replacement
          start = end
    return state

  def _update_metrics(self) -> None:
    self.metrics["joint_pos_error"] += (self.joint_pos - self.robot_joint_pos).norm(dim=-1)
    self.metrics["anchor_pos_error"] += (
      self.body_pos_w[:, self.anchor_index] - self.robot_body_pos_w[:, self.anchor_index]
    ).norm(dim=-1)

  def _resample_command(self, env_ids: torch.Tensor) -> None:
    if self.cfg.random_start:
      self._frame_progress[env_ids] = torch.randint(self.num_frames, (len(env_ids),), device=self.device).float()
    else:
      self._frame_progress[env_ids] = 0.0
    self._frame[env_ids] = self._frame_progress[env_ids].long()

  def _update_command(self) -> None:
    self._frame_progress += self.fps * self._env.step_dt
    if self.cfg.loop:
      self._frame_progress.remainder_(self.num_frames)
    else:
      self._frame_progress.clamp_(max=self.num_frames - 1)
    self._frame.copy_(self._frame_progress.long())


def _motion(env: "ManagerBasedRlEnv", command_name: str) -> MotionReferenceCommand:
  command = env.command_manager.get_term(command_name)
  if not isinstance(command, MotionReferenceCommand):
    raise TypeError(f"'{command_name}' must be a MotionReferenceCommand")
  return command


def motion_reference(env: "ManagerBasedRlEnv", command_name: str = "motion") -> torch.Tensor:
  """Deployable tracker input: named q/dq reference at the current phase."""
  return _motion(env, command_name).command


def motion_reference_preview(
  env: "ManagerBasedRlEnv", command_name: str = "motion", frame_offset: int = 1
) -> torch.Tensor:
  """Causal one-frame motion-reference preview for the policy actor."""
  return _motion(env, command_name).joint_reference_frame_offset(frame_offset)


def motion_clip_complete(env: "ManagerBasedRlEnv", command_name: str = "motion") -> torch.Tensor:
  """Terminate a non-looping imitation episode at the clip's terminal pose."""
  command = _motion(env, command_name)
  if command.cfg.loop:
    return torch.zeros(env.num_envs, dtype=torch.bool, device=env.device)
  return command._frame >= command.num_frames - 1


def motion_anchor_error(env: "ManagerBasedRlEnv", command_name: str = "motion") -> torch.Tensor:
  command = _motion(env, command_name)
  p = command.body_pos_w[:, command.anchor_index] - command.robot_body_pos_w[:, command.anchor_index]
  q_ref = command.body_quat_w[:, command.anchor_index]
  q = command.robot_body_quat_w[:, command.anchor_index]
  # q and -q encode the same orientation.
  ori = 1.0 - (q_ref * q).sum(dim=-1, keepdim=True).abs()
  return torch.cat([p, ori], dim=-1)


def motion_body_targets(env: "ManagerBasedRlEnv", command_name: str = "motion") -> torch.Tensor:
  return _motion(env, command_name).aligned_body_pos_w().flatten(1)


def motion_reference_centroidal(env: "ManagerBasedRlEnv", command_name: str = "motion") -> torch.Tensor:
  """Reference CoM/velocity/momentum and contact vectors relative to CoM.

  Layout: ``[c(3), dc(3), l(3), h(3), r_contact(C*3)]``.  The geometric
  vectors are reconstructed from the reference motion and matched robot model.
  """
  command = _motion(env, command_name)
  reference = command.reference_centroidal
  return torch.cat((
    reference.com_pos_w,
    reference.com_vel_w,
    reference.linear_momentum_w,
    reference.angular_momentum_w,
    reference.contact_pos_rel_com_w.flatten(1),
  ), dim=-1)


def motion_joint_error_exp(env: "ManagerBasedRlEnv", command_name: str = "motion", std: float = 0.4) -> torch.Tensor:
  command = _motion(env, command_name)
  return torch.exp(-(command.joint_pos - command.robot_joint_pos).square().mean(dim=-1) / std**2)


def motion_joint_vel_error_exp(env: "ManagerBasedRlEnv", command_name: str = "motion", std: float = 2.0) -> torch.Tensor:
  command = _motion(env, command_name)
  return torch.exp(-(command.joint_vel - command.robot_joint_vel).square().mean(dim=-1) / std**2)


def motion_relative_body_position_error_exp(
  env: "ManagerBasedRlEnv", command_name: str = "motion", std: float = 0.3
) -> torch.Tensor:
  command = _motion(env, command_name)
  return torch.exp(-(command.aligned_body_pos_w() - command.robot_body_pos_w).square().sum(dim=-1).mean(dim=-1) / std**2)


def motion_anchor_position_error_exp(
  env: "ManagerBasedRlEnv", command_name: str = "motion", std: float = 0.3
) -> torch.Tensor:
  command = _motion(env, command_name)
  error = (command.body_pos_w[:, command.anchor_index] - command.robot_body_pos_w[:, command.anchor_index]).square().sum(dim=-1)
  return torch.exp(-error / std**2)


def tracking_success(
  env: "ManagerBasedRlEnv",
  command_name: str = "motion",
  joint_rms_threshold: float = 0.35,
  anchor_position_threshold: float = 0.25,
  upright_cos_threshold: float = 0.5,
) -> torch.Tensor:
  """Binary whole-body tracking-success signal for the task critic.

  It is intentionally separate from dense ``motion_*`` imitation rewards:
  success requires simultaneously small joint error, small anchor error, and
  an upright torso.  The reward uses no future clip information and therefore
  remains valid for non-periodic reference tracking.
  """
  command = _motion(env, command_name)
  joint_rms = (command.joint_pos - command.robot_joint_pos).square().mean(dim=-1).sqrt()
  anchor_error = (
    command.body_pos_w[:, command.anchor_index] - command.robot_body_pos_w[:, command.anchor_index]
  ).norm(dim=-1)
  # projected_gravity_b == [0, 0, -1] for an upright base on flat gravity.
  upright_cos = -command.robot.data.projected_gravity_b[:, 2]
  return (
    (joint_rms <= joint_rms_threshold)
    & (anchor_error <= anchor_position_threshold)
    & (upright_cos >= upright_cos_threshold)
  ).to(dtype=joint_rms.dtype)
